// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public interface _FaceAlgSvrOperationsNC
{
    FaceInfo[] Detect(Image img);

    FaceInfo[] DetectSimple(Image img);

    float MatchImage(Image img1, Image img2);

    float MatchFeatures(float[] fea1, float[] fea2);

    FaceInfoEx[] RecognizeImage(String faceSetId, Image img, int n);

    RecogResult[] RecognizeFeatures(String faceSetId, float[] fea, int n);

    FaceInfo[] DetectNIR(Image img);

    FaceInfo[] DetectSimpleNIR(Image img);

    float MatchImageNIR(Image img1, Image img2);

    float MatchFeaturesNIR(float[] fea1, float[] fea2);

    FaceInfoEx[] RecognizeImageNIR(String faceSetId, Image img, int n);

    RecogResult[] RecognizeFeaturesNIR(String faceSetId, float[] fea, int n);

    boolean CreateFaceSet(String id, FaceAlgType type);

    boolean DeleteFaceSet(String id);

    int GetFaceCount(String faceSetId);

    String[] GetAllFaceId(String faceSetId);

    boolean AddFace(String faceSetId, float[] fea, String faceId);

    boolean DeleteFace(String faceSetId, String faceId);
}
