// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public interface _FaceAlgSvrOperations
{
    FaceInfo[] Detect(Image img, Ice.Current __current);

    FaceInfo[] DetectSimple(Image img, Ice.Current __current);

    float MatchImage(Image img1, Image img2, Ice.Current __current);

    float MatchFeatures(float[] fea1, float[] fea2, Ice.Current __current);

    FaceInfoEx[] RecognizeImage(String faceSetId, Image img, int n, Ice.Current __current);

    RecogResult[] RecognizeFeatures(String faceSetId, float[] fea, int n, Ice.Current __current);

    FaceInfo[] DetectNIR(Image img, Ice.Current __current);

    FaceInfo[] DetectSimpleNIR(Image img, Ice.Current __current);

    float MatchImageNIR(Image img1, Image img2, Ice.Current __current);

    float MatchFeaturesNIR(float[] fea1, float[] fea2, Ice.Current __current);

    FaceInfoEx[] RecognizeImageNIR(String faceSetId, Image img, int n, Ice.Current __current);

    RecogResult[] RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, Ice.Current __current);

    boolean CreateFaceSet(String id, FaceAlgType type, Ice.Current __current);

    boolean DeleteFaceSet(String id, Ice.Current __current);

    int GetFaceCount(String faceSetId, Ice.Current __current);

    String[] GetAllFaceId(String faceSetId, Ice.Current __current);

    boolean AddFace(String faceSetId, float[] fea, String faceId, Ice.Current __current);

    boolean DeleteFace(String faceSetId, String faceId, Ice.Current __current);
}
