// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public interface FaceAlgSvrPrx extends Ice.ObjectPrx
{
    public FaceInfo[] Detect(Image img);

    public FaceInfo[] Detect(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Detect(Image img);

    public Ice.AsyncResult begin_Detect(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Detect(Image img, Ice.Callback __cb);

    public Ice.AsyncResult begin_Detect(Image img, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_Detect(Image img, Callback_FaceAlgSvr_Detect __cb);

    public Ice.AsyncResult begin_Detect(Image img, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_Detect __cb);

    public Ice.AsyncResult begin_Detect(Image img, 
                                        IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_Detect(Image img, 
                                        IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_Detect(Image img, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_Detect(Image img, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public FaceInfo[] end_Detect(Ice.AsyncResult __result);

    public FaceInfo[] DetectSimple(Image img);

    public FaceInfo[] DetectSimple(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DetectSimple(Image img);

    public Ice.AsyncResult begin_DetectSimple(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DetectSimple(Image img, Ice.Callback __cb);

    public Ice.AsyncResult begin_DetectSimple(Image img, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_DetectSimple(Image img, Callback_FaceAlgSvr_DetectSimple __cb);

    public Ice.AsyncResult begin_DetectSimple(Image img, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_DetectSimple __cb);

    public Ice.AsyncResult begin_DetectSimple(Image img, 
                                              IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DetectSimple(Image img, 
                                              IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_DetectSimple(Image img, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DetectSimple(Image img, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public FaceInfo[] end_DetectSimple(Ice.AsyncResult __result);

    public float MatchImage(Image img1, Image img2);

    public float MatchImage(Image img1, Image img2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchImage(Image img1, Image img2);

    public Ice.AsyncResult begin_MatchImage(Image img1, Image img2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchImage(Image img1, Image img2, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchImage(Image img1, Image img2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchImage(Image img1, Image img2, Callback_FaceAlgSvr_MatchImage __cb);

    public Ice.AsyncResult begin_MatchImage(Image img1, Image img2, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_MatchImage __cb);

    public Ice.AsyncResult begin_MatchImage(Image img1, 
                                            Image img2, 
                                            IceInternal.Functional_FloatCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchImage(Image img1, 
                                            Image img2, 
                                            IceInternal.Functional_FloatCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_MatchImage(Image img1, 
                                            Image img2, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_FloatCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchImage(Image img1, 
                                            Image img2, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_FloatCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public float end_MatchImage(Ice.AsyncResult __result);

    public float MatchFeatures(float[] fea1, float[] fea2);

    public float MatchFeatures(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, float[] fea2);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, float[] fea2, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, float[] fea2, Callback_FaceAlgSvr_MatchFeatures __cb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_MatchFeatures __cb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, 
                                               float[] fea2, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, 
                                               float[] fea2, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, 
                                               float[] fea2, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchFeatures(float[] fea1, 
                                               float[] fea2, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public float end_MatchFeatures(Ice.AsyncResult __result);

    public FaceInfoEx[] RecognizeImage(String faceSetId, Image img, int n);

    public FaceInfoEx[] RecognizeImage(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, Image img, int n);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, Image img, int n, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, Image img, int n, Callback_FaceAlgSvr_RecognizeImage __cb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_RecognizeImage __cb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, 
                                                Image img, 
                                                int n, 
                                                IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, 
                                                Image img, 
                                                int n, 
                                                IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, 
                                                Image img, 
                                                int n, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeImage(String faceSetId, 
                                                Image img, 
                                                int n, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public FaceInfoEx[] end_RecognizeImage(Ice.AsyncResult __result);

    public RecogResult[] RecognizeFeatures(String faceSetId, float[] fea, int n);

    public RecogResult[] RecognizeFeatures(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, float[] fea, int n);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, float[] fea, int n, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, float[] fea, int n, Callback_FaceAlgSvr_RecognizeFeatures __cb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_RecognizeFeatures __cb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, 
                                                   float[] fea, 
                                                   int n, 
                                                   IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, 
                                                   float[] fea, 
                                                   int n, 
                                                   IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, 
                                                   float[] fea, 
                                                   int n, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeFeatures(String faceSetId, 
                                                   float[] fea, 
                                                   int n, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public RecogResult[] end_RecognizeFeatures(Ice.AsyncResult __result);

    public FaceInfo[] DetectNIR(Image img);

    public FaceInfo[] DetectNIR(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DetectNIR(Image img);

    public Ice.AsyncResult begin_DetectNIR(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DetectNIR(Image img, Ice.Callback __cb);

    public Ice.AsyncResult begin_DetectNIR(Image img, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_DetectNIR(Image img, Callback_FaceAlgSvr_DetectNIR __cb);

    public Ice.AsyncResult begin_DetectNIR(Image img, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_DetectNIR __cb);

    public Ice.AsyncResult begin_DetectNIR(Image img, 
                                           IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DetectNIR(Image img, 
                                           IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_DetectNIR(Image img, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DetectNIR(Image img, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public FaceInfo[] end_DetectNIR(Ice.AsyncResult __result);

    public FaceInfo[] DetectSimpleNIR(Image img);

    public FaceInfo[] DetectSimpleNIR(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, Ice.Callback __cb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, Callback_FaceAlgSvr_DetectSimpleNIR __cb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_DetectSimpleNIR __cb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, 
                                                 IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, 
                                                 IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DetectSimpleNIR(Image img, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<FaceInfo[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public FaceInfo[] end_DetectSimpleNIR(Ice.AsyncResult __result);

    public float MatchImageNIR(Image img1, Image img2);

    public float MatchImageNIR(Image img1, Image img2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, Image img2);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, Image img2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, Image img2, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, Image img2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, Image img2, Callback_FaceAlgSvr_MatchImageNIR __cb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, Image img2, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_MatchImageNIR __cb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, 
                                               Image img2, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, 
                                               Image img2, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, 
                                               Image img2, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchImageNIR(Image img1, 
                                               Image img2, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_FloatCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public float end_MatchImageNIR(Ice.AsyncResult __result);

    public float MatchFeaturesNIR(float[] fea1, float[] fea2);

    public float MatchFeaturesNIR(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, float[] fea2);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, float[] fea2, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, float[] fea2, Callback_FaceAlgSvr_MatchFeaturesNIR __cb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, float[] fea2, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_MatchFeaturesNIR __cb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, 
                                                  float[] fea2, 
                                                  IceInternal.Functional_FloatCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, 
                                                  float[] fea2, 
                                                  IceInternal.Functional_FloatCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, 
                                                  float[] fea2, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_FloatCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_MatchFeaturesNIR(float[] fea1, 
                                                  float[] fea2, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_FloatCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public float end_MatchFeaturesNIR(Ice.AsyncResult __result);

    public FaceInfoEx[] RecognizeImageNIR(String faceSetId, Image img, int n);

    public FaceInfoEx[] RecognizeImageNIR(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, Image img, int n);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, Image img, int n, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, Image img, int n, Callback_FaceAlgSvr_RecognizeImageNIR __cb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, Image img, int n, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_RecognizeImageNIR __cb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, 
                                                   Image img, 
                                                   int n, 
                                                   IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, 
                                                   Image img, 
                                                   int n, 
                                                   IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, 
                                                   Image img, 
                                                   int n, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeImageNIR(String faceSetId, 
                                                   Image img, 
                                                   int n, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<FaceInfoEx[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public FaceInfoEx[] end_RecognizeImageNIR(Ice.AsyncResult __result);

    public RecogResult[] RecognizeFeaturesNIR(String faceSetId, float[] fea, int n);

    public RecogResult[] RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, float[] fea, int n);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, Callback_FaceAlgSvr_RecognizeFeaturesNIR __cb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, float[] fea, int n, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_RecognizeFeaturesNIR __cb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, 
                                                      float[] fea, 
                                                      int n, 
                                                      IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, 
                                                      float[] fea, 
                                                      int n, 
                                                      IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, 
                                                      float[] fea, 
                                                      int n, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_RecognizeFeaturesNIR(String faceSetId, 
                                                      float[] fea, 
                                                      int n, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<RecogResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb);

    public RecogResult[] end_RecognizeFeaturesNIR(Ice.AsyncResult __result);

    public boolean CreateFaceSet(String id, FaceAlgType type);

    public boolean CreateFaceSet(String id, FaceAlgType type, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_CreateFaceSet(String id, FaceAlgType type);

    public Ice.AsyncResult begin_CreateFaceSet(String id, FaceAlgType type, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_CreateFaceSet(String id, FaceAlgType type, Ice.Callback __cb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, FaceAlgType type, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, FaceAlgType type, Callback_FaceAlgSvr_CreateFaceSet __cb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, FaceAlgType type, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_CreateFaceSet __cb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, 
                                               FaceAlgType type, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, 
                                               FaceAlgType type, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, 
                                               FaceAlgType type, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_CreateFaceSet(String id, 
                                               FaceAlgType type, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_CreateFaceSet(Ice.AsyncResult __result);

    public boolean DeleteFaceSet(String id);

    public boolean DeleteFaceSet(String id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DeleteFaceSet(String id);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, Ice.Callback __cb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, Callback_FaceAlgSvr_DeleteFaceSet __cb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_DeleteFaceSet __cb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DeleteFaceSet(String id, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_DeleteFaceSet(Ice.AsyncResult __result);

    public int GetFaceCount(String faceSetId);

    public int GetFaceCount(String faceSetId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, Callback_FaceAlgSvr_GetFaceCount __cb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_GetFaceCount __cb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, 
                                              IceInternal.Functional_IntCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, 
                                              IceInternal.Functional_IntCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_IntCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_GetFaceCount(String faceSetId, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_IntCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public int end_GetFaceCount(Ice.AsyncResult __result);

    public String[] GetAllFaceId(String faceSetId);

    public String[] GetAllFaceId(String faceSetId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, Callback_FaceAlgSvr_GetAllFaceId __cb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_GetAllFaceId __cb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, 
                                              IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, 
                                              IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_GetAllFaceId(String faceSetId, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_GetAllFaceId(Ice.AsyncResult __result);

    public boolean AddFace(String faceSetId, float[] fea, String faceId);

    public boolean AddFace(String faceSetId, float[] fea, String faceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddFace(String faceSetId, float[] fea, String faceId);

    public Ice.AsyncResult begin_AddFace(String faceSetId, float[] fea, String faceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddFace(String faceSetId, float[] fea, String faceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, float[] fea, String faceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, float[] fea, String faceId, Callback_FaceAlgSvr_AddFace __cb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, float[] fea, String faceId, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_AddFace __cb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, 
                                         float[] fea, 
                                         String faceId, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, 
                                         float[] fea, 
                                         String faceId, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, 
                                         float[] fea, 
                                         String faceId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_AddFace(String faceSetId, 
                                         float[] fea, 
                                         String faceId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_AddFace(Ice.AsyncResult __result);

    public boolean DeleteFace(String faceSetId, String faceId);

    public boolean DeleteFace(String faceSetId, String faceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, String faceId);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, String faceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, String faceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, String faceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, String faceId, Callback_FaceAlgSvr_DeleteFace __cb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, String faceId, java.util.Map<String, String> __ctx, Callback_FaceAlgSvr_DeleteFace __cb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, 
                                            String faceId, 
                                            IceInternal.Functional_BoolCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, 
                                            String faceId, 
                                            IceInternal.Functional_BoolCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, 
                                            String faceId, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_BoolCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_DeleteFace(String faceSetId, 
                                            String faceId, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_BoolCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_DeleteFace(Ice.AsyncResult __result);
}
