// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public enum FaceAlgType implements java.io.Serializable
{
    
    VIS(0),
    
    NIR(1);

    public int
    value()
    {
        return __value;
    }

    public static FaceAlgType
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return VIS;
        case 1:
            return NIR;
        }
        return null;
    }

    private
    FaceAlgType(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 1);
    }

    public static void
    __write(IceInternal.BasicStream __os, FaceAlgType __v)
    {
        if(__v == null)
        {
            __os.writeEnum(FaceAlg.FaceAlgType.VIS.value(), 1);
        }
        else
        {
            __os.writeEnum(__v.value(), 1);
        }
    }

    public static FaceAlgType
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(1);
        return __validate(__v);
    }

    private static FaceAlgType
    __validate(int __v)
    {
        final FaceAlgType __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
