// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public interface FaceAlgSvr extends Ice.Object,
                                    _FaceAlgSvrOperations, _FaceAlgSvrOperationsNC
{
    public static final String ice_staticId = "::FaceAlg::FaceAlgSvr";

    public static final long serialVersionUID = -17914870L;
}
