// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public class FPoint implements java.lang.Cloneable, java.io.Serializable
{
    public double x;

    public double y;

    public FPoint()
    {
    }

    public FPoint(double x, double y)
    {
        this.x = x;
        this.y = y;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FPoint _r = null;
        if(rhs instanceof FPoint)
        {
            _r = (FPoint)rhs;
        }

        if(_r != null)
        {
            if(x != _r.x)
            {
                return false;
            }
            if(y != _r.y)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::FaceAlg::FPoint");
        __h = IceInternal.HashUtil.hashAdd(__h, x);
        __h = IceInternal.HashUtil.hashAdd(__h, y);
        return __h;
    }

    public FPoint
    clone()
    {
        FPoint c = null;
        try
        {
            c = (FPoint)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeDouble(x);
        __os.writeDouble(y);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        x = __is.readDouble();
        y = __is.readDouble();
    }

    static public void
    __write(IceInternal.BasicStream __os, FPoint __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public FPoint
    __read(IceInternal.BasicStream __is, FPoint __v)
    {
        if(__v == null)
        {
             __v = new FPoint();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final FPoint __nullMarshalValue = new FPoint();

    public static final long serialVersionUID = 1589031083L;
}
