// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FaceAlg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FaceAlg;

public final class RecogResultHolder extends Ice.Holder<RecogResult>
{
    public
    RecogResultHolder()
    {
    }

    public
    RecogResultHolder(RecogResult value)
    {
        super(value);
    }
}
